# Generated by Django 4.2.3 on 2023-08-02 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeartHeal', '0002_calendar_meeting_user_assigned_doctor_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='meeting',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='HeartHeal.meeting'),
        ),
    ]
