# Generated by Django 4.2.3 on 2023-08-03 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeartHeal', '0003_alter_day_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='calendar',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='HeartHeal.calendar'),
        ),
    ]
