# Generated by Django 4.2.3 on 2023-08-03 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeartHeal', '0004_alter_day_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeartHeal.meeting'),
        ),
    ]
