# Generated by Django 4.2.3 on 2023-08-04 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeartHeal', '0006_alter_user_assigned_doctor_examination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
