# Generated by Django 4.2.3 on 2023-08-04 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeartHeal', '0010_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='title',
        ),
    ]
