# Generated by Django 4.2.3 on 2023-08-05 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeartHeal', '0011_remove_note_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='time',
            field=models.TimeField(default=datetime.time(1, 0)),
        ),
    ]
