# Generated by Django 4.2.3 on 2023-08-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeartHeal', '0013_remove_meeting_available_remove_meeting_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='when',
            field=models.IntegerField(default=9),
            preserve_default=False,
        ),
    ]
