# Generated by Django 4.2.3 on 2023-08-05 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeartHeal', '0014_meeting_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='meeting',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeartHeal.meeting'),
        ),
    ]
