# Generated by Django 4.2.3 on 2023-08-18 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeartHeal', '0021_goal_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='HeartHeal.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HeartHeal.user'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeartHeal.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeartHeal.user')),
            ],
        ),
    ]
