# Generated by Django 4.2.3 on 2023-08-20 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeartHeal', '0026_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 20, 10, 21, 56, 418689, tzinfo=datetime.timezone.utc)),
        ),
    ]
