# Generated by Django 4.2.3 on 2023-08-22 03:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeartHeal', '0027_alter_comment_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 3, 7, 19, 126147, tzinfo=datetime.timezone.utc)),
        ),
    ]
