# Generated by Django 4.2.3 on 2023-08-23 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeartHeal', '0028_goal_done_task_done_alter_comment_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 11, 20, 54, 395366, tzinfo=datetime.timezone.utc)),
        ),
    ]
