# Generated by Django 4.2.3 on 2023-08-23 12:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HeartHeal', '0029_alter_comment_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('duration', models.CharField(max_length=50)),
                ('video', models.FileField(blank=True, null=True, upload_to='video/')),
            ],
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=50)),
                ('timestamp', models.DateField(default=datetime.date(2023, 8, 23))),
            ],
        ),
        migrations.CreateModel(
            name='Practice_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 12, 37, 25, 995836, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='What_yll_learn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeartHeal.practice')),
            ],
        ),
        migrations.AddField(
            model_name='practice',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HeartHeal.practice_category'),
        ),
        migrations.CreateModel(
            name='Module_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeartHeal.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeartHeal.user')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='practice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HeartHeal.practice'),
        ),
    ]
