# Generated by Django 4.2.3 on 2023-08-24 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeartHeal', '0030_module_practice_practice_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 24, 6, 16, 5, 809324, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='practice',
            name='timestamp',
            field=models.DateField(default=datetime.date(2023, 8, 24)),
        ),
    ]
