# Generated by Django 4.2.3 on 2023-08-24 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeartHeal', '0031_practice_by_alter_comment_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='content_overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 24, 6, 20, 30, 541614, tzinfo=datetime.timezone.utc)),
        ),
    ]
