# Generated by Django 4.2.3 on 2023-08-24 06:23

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeartHeal', '0032_practice_content_overview_alter_comment_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 24, 6, 23, 49, 507735, tzinfo=datetime.timezone.utc)),
        ),
    ]
