# Generated by Django 4.2.3 on 2023-08-24 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeartHeal', '0033_module_content_alter_comment_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='video_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 24, 6, 26, 38, 894442, tzinfo=datetime.timezone.utc)),
        ),
    ]
