# Generated by Django 4.2.3 on 2023-08-24 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeartHeal', '0035_module_overview_alter_comment_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='image',
            field=models.ImageField(blank=True, upload_to='imgs/'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 24, 6, 36, 28, 343272, tzinfo=datetime.timezone.utc)),
        ),
    ]
